force-app/main/default/objects/Opportunity/fields/DeliveryInstallationStatus__c.field-meta.xml
<CustomField>
    <fullName>DeliveryInstallationStatus__c</fullName>
    <label>Delivery/Installation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Yet to begin</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description
  >Shadow object containing records loaded from an inbound integration with the external PMS. It is a child to Opportunities as the originating source.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Billable_Amount__c.field-meta.xml
<CustomField>
    <fullName>Billable_Amount__c</fullName>
    <label>Billable Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectRef__c.field-meta.xml
<CustomField>
    <fullName>ProjectRef__c</fullName>
    <externalId>true</externalId>
    <label>ProjectRef</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ProjectRESTService.cls
@RestResource(urlMapping='/project/*')
global class ProjectRESTService {
    //Implement service logic here
    @HttpPost
    global static String postProjectData(
        String ProjectRef,
        String ProjectName,
        String OpportunityId,
        Date startDate,
        Date endDate,
        Double Amount,
        String Status
    ) {
        String returnMessage = '';
        System.debug('HELP');
        Savepoint objSavePoint = Database.setSavepoint();

        try {
            if (OpportunityId != null && OpportunityId.trim().length() > 0) {
                Opportunity opp = new Opportunity(Id = opportunityId);
                opp.DeliveryInstallationStatus__c = 'In progress';
                update opp;

                Project__c project = new Project__c(ProjectRef__c = ProjectRef);
                project.Name = ProjectName;
                project.Opportunity__c = OpportunityId;
                project.Start_Date__c = startDate;
                project.End_Date__c = endDate;
                project.Billable_Amount__c = Amount;
                upsert project;

                returnMessage = 'OK';
            } else {
                returnMessage = 'Invalid work';
            }
        } catch (Exception e) {
            Database.RollBack(objSavePoint);

            returnMessage = 'Exception is ' + e.getMessage();
        }

        return returnMessage;
    }
}